"use client";

import React, { useState, useMemo } from "react";
import {
  BsPersonFill,
  BsDropletFill,
  BsGeoAltFill,
  BsImageFill,
  BsCheckCircleFill,
  BsArrowLeft,
  BsArrowRight,
} from "react-icons/bs";
import styles from "../styles.module.scss";
import { APIService, isAPISuccess } from "@/service/api/api";

export default function CriarSolicitacao() {
  const [currentStep, setCurrentStep] = useState(1);
  const totalSteps = 4;
  const api = useMemo(() => new APIService(), []);
  const [formData, setFormData] = useState({
    nome: "",
    telefone: "",
    tipoSanguineo: "",
    quantidade: 1,
    endereco: "",
    datainicio: "",
    datatermino: "",
    descricao: "",
  });

  const [isSubmitting, setIsSubmitting] = useState(false);

  const steps = [
    { number: 1, title: "Dados do Paciente", icon: BsPersonFill },
    { number: 2, title: "Doação", icon: BsDropletFill },
    { number: 3, title: "Local e Período", icon: BsGeoAltFill },
    { number: 4, title: "Informações Extras", icon: BsImageFill },
  ];

  const handleNext = () => {
    if (currentStep < totalSteps) {
      setCurrentStep((s) => s + 1);
      // remove foco do elemento atual para evitar que o DOM reutilize o nó
      // e transforme o botão em 'submit' durante o re-render
      try {
        (document.activeElement as HTMLElement)?.blur();
      } catch {}
    }
  };

  const handlePrevious = () => {
    if (currentStep > 1) {
      setCurrentStep(currentStep - 1);

    }
  };

  const handleChange = (field: string, value: any) => {
    setFormData({ ...formData, [field]: value });
  };

  // Mantemos o handler onSubmit do form com preventDefault para evitar submits
  // automáticos (por Enter ou re-render). O envio real é feito por
  // performSubmit(), chamado explicitamente pelo botão.
  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
  };

  const submitNonceRef = React.useRef<string | null>(null);

  const performSubmit = async (nonce?: string) => {
    // Require a matching nonce generated by the user's button click to proceed
    if (!nonce || submitNonceRef.current !== nonce) {
      return;
    }
    submitNonceRef.current = null;
    if (currentStep < totalSteps) {
      return;
    }
    if (isSubmitting) {
      return;
    }
    setIsSubmitting(true);
  
    const payload = {
      name: formData.nome,
      phone: formData.telefone,
      bloodType: formData.tipoSanguineo,
      quantity: Number(formData.quantidade),
      address: formData.endereco,
      startDate: formData.datainicio || null,
      endDate: formData.datatermino || null,
      description: formData.descricao || "",
    };

    try {
      const url = api.getDonationServiceUrl("donations");
      const result = await api.post(url, payload);
      if (!isMounted.current) return;
      if (isAPISuccess(result)) {
        setTimeout(() => {
          if (!isMounted.current) return;
          setFormData({
            nome: "",
            telefone: "",
            tipoSanguineo: "",
            quantidade: 1,
            endereco: "",
            datainicio: "",
            datatermino: "",
            descricao: "",
          });
          setCurrentStep(1);
        }, 50);
      } else {
        console.error("Erro ao criar solicitação:", result.message);
      }
    } catch (error) {
          console.error("💥 Erro no envio:", error);
    } finally {
      if (isMounted.current) setIsSubmitting(false);
    }
  };
  const isMounted = React.useRef(true);
  const formRef = React.useRef<HTMLDivElement | null>(null);

  React.useEffect(() => {
    return () => {
      isMounted.current = false;
    };
  }, []);

  return (
    <main className={styles.container}>
      <div className={styles.content}>
        {/* Header */}
        <div className={styles.header}>
          <h1 className={styles.title}>
            Criar Solicitação de
            <span className={styles.highlight}>Doação</span>
          </h1>
          <p className={styles.subtitle}>
            Preencha as informações necessárias para que doadores possam
            encontrar sua solicitação e ajudar quem precisa.
          </p>
        </div>

        {/* Progress Stepper */}
        <div className={styles.stepper}>
          {steps.map((step, index) => {
            const StepIcon = step.icon;
            const isActive = currentStep === step.number;
            const isCompleted = currentStep > step.number;

            return (
              <div key={step.number} className={styles.stepItem}>
                <div
                  className={`${styles.stepCircle} ${
                    isActive ? styles.active : ""
                  } ${isCompleted ? styles.completed : ""}`}
                >
                  {isCompleted ? (
                    <BsCheckCircleFill className={styles.checkIcon} />
                  ) : (
                    <StepIcon className={styles.stepIcon} />
                  )}
                </div>
                <div className={styles.stepLabel}>
                  <span className={styles.stepNumber}>Passo {step.number}</span>
                  <span className={styles.stepTitle}>{step.title}</span>
                </div>
                {index < steps.length - 1 && (
                  <div
                    className={`${styles.stepLine} ${
                      isCompleted ? styles.completed : ""
                    }`}
                  />
                )}
              </div>
            );
          })}
        </div>

        {/* Form */}
        <div
          ref={(el) => { formRef.current = el as HTMLDivElement; return; }}
          role="form"
          onSubmit={handleSubmit as any}
          onKeyDown={(e) => {
            if (e.key === "Enter") {
                const target = e.target as HTMLElement;
                const tag = target.tagName.toLowerCase();
                const type = (target as HTMLInputElement).type;

                // Previne o submit se Enter for pressionado em qualquer lugar que não seja um textarea
                // ou se o elemento focado não for um botão de submit explícito no último passo
                // Previne o submit se Enter for pressionado em qualquer lugar que não seja um textarea
                // e se o currentStep não for o último passo, ou se o elemento focado não for um botão de submit explícito
                if (tag !== "textarea" && !(tag === "button" && type === "submit" && currentStep === totalSteps)) {
                    e.preventDefault();
                    console.warn(`⛔ Enter bloqueado no campo: <${tag} type="${type}">. Submit prevented.`);
                }
            }
            }}
          className={styles.form}
        >
          <div className={styles.formCard}>
            {/* Step 1: Patient Data */}
            {currentStep === 1 && (
              <div className={styles.stepContent}>
                <h2 className={styles.stepHeading}>
                  <BsPersonFill className={styles.headingIcon} />
                  Dados do Paciente
                </h2>
                <div className={styles.formGrid}>
                  <div className={styles.formGroup}>
                    <label htmlFor="nome" className={styles.label}>
                      Nome do paciente
                      <span className={styles.required}>*</span>
                    </label>
                    <input
                        type="text"
                        className={styles.input}
                        id="nome"
                        placeholder="Digite o nome completo"
                        value={formData.nome}
                        onChange={(e) => handleChange("nome", e.target.value)}
                        required
                      />
                  </div>

                  <div className={styles.formGroup}>
                    <label htmlFor="telefone" className={styles.label}>
                      Telefone para contato
                      <span className={styles.required}>*</span>
                    </label>
                    <input
                      type="tel"
                      className={styles.input}
                      id="telefone"
                      placeholder="(00) 00000-0000"
                      value={formData.telefone}
                      onChange={(e) => handleChange("telefone", e.target.value)}
                      required
                    />
                    <span className={styles.helpText}>
                      Número para contato sobre a doação
                    </span>
                  </div>
                </div>
              </div>
            )}

            {/* Step 2: Blood Info */}
            {currentStep === 2 && (
              <div className={styles.stepContent}>
                <h2 className={styles.stepHeading}>
                  <BsDropletFill className={styles.headingIcon} />
                  Informações sobre a Doação
                </h2>
                <div className={styles.formGrid}>
                  <div className={styles.formGroup}>
                    <label htmlFor="tipoSanguineo" className={styles.label}>
                      Tipo sanguíneo <span className={styles.required}>*</span>
                    </label>
                    <select
                      className={styles.select}
                      id="tipoSanguineo"
                      value={formData.tipoSanguineo}
                      onChange={(e) => handleChange("tipoSanguineo", e.target.value)}
                      required
                    >
                      <option value="" disabled>
                        Selecione o tipo sanguíneo
                      </option>
                      <option value="" disabled>Selecione o tipo sanguíneo</option>
                        <option value="A+">A+</option>
                        <option value="A-">A-</option>
                        <option value="B+">B+</option>
                        <option value="B-">B-</option>
                        <option value="AB+">AB+</option>
                        <option value="AB-">AB-</option>
                        <option value="O+">O+</option>
                        <option value="O-">O-</option>
                    </select>
                  </div>

                  <div className={styles.formGroup}>
                    <label htmlFor="quantidade" className={styles.label}>
                      Quantidade de bolsas
                      <span className={styles.required}>*</span>
                    </label>
                    <input
                        type="number"
                        className={styles.input}
                        id="quantidade"
                        placeholder="Ex: 2"
                        min="1"
                        value={formData.quantidade}
                        onChange={(e) => handleChange("quantidade", e.target.value)}
                        required
                      />
                    <span className={styles.helpText}>
                      Quantidade necessária para a transfusão
                    </span>
                  </div>
                </div>
              </div>
            )}

            {/* Step 3: Location & Period */}
            {currentStep === 3 && (
              <div className={styles.stepContent}>
                <h2 className={styles.stepHeading}>
                  <BsGeoAltFill className={styles.headingIcon} />
                  Local e Período
                </h2>
                <div className={styles.formGrid}>
                  <div className={`${styles.formGroup} ${styles.fullWidth}`}>
                    <label htmlFor="endereco" className={styles.label}>
                      Endereço para doação
                      <span className={styles.required}>*</span>
                    </label>
                    <input
                      type="text"
                      className={styles.input}
                      id="endereco"
                      placeholder="Hospital, clínica ou hemocentro"
                      value={formData.endereco}
                      onChange={(e) => handleChange("endereco", e.target.value)}
                      required
                    />
                    <span className={styles.helpText}>
                      Informe o local onde a doação deve ser realizada
                    </span>
                  </div>

                  <div className={styles.formGroup}>
                    <label htmlFor="datainicio" className={styles.label}>
                      Data de início
                    </label>
                    <input
                      type="date"
                      className={styles.input}
                      id="datainicio"
                      value={formData.datainicio}
                      onChange={(e) => handleChange("datainicio", e.target.value)}
                    />
                  </div>

                  <div className={styles.formGroup}>
                    <label htmlFor="datatermino" className={styles.label}>
                      Data de término
                    </label>
                    <input
                      type="date"
                      className={styles.input}
                      id="datatermino"
                      value={formData.datatermino}
                      onChange={(e) => handleChange("datatermino", e.target.value)}
                    />
                  </div>
                </div>
              </div>
            )}

            {/* Step 4: Extra Info */}
            {currentStep === 4 && (
              <div className={styles.stepContent}>
                <h2 className={styles.stepHeading}>
                  <BsImageFill className={styles.headingIcon} />
                  Informações Complementares
                </h2>
                <div className={styles.formGrid}>
                  <div className={`${styles.formGroup} ${styles.fullWidth}`}>
                    <label htmlFor="descricao" className={styles.label}>
                      Descrição da solicitação
                    </label>
                    <textarea
                      className={styles.textarea}
                      id="descricao"
                      rows={5}
                      placeholder="Adicione informações adicionais que possam ajudar os doadores (opcional)"
                      value={formData.descricao}
                      onChange={(e) => handleChange("descricao", e.target.value)}
                    ></textarea>
                    <span className={styles.helpText}>
                      Informações sobre a urgência, histórico ou condições
                      especiais
                    </span>
                  </div>

                  <div className={`${styles.formGroup} ${styles.fullWidth}`}>
                    <label htmlFor="formFile" className={styles.label}>
                      Foto do paciente (opcional)
                    </label>
                    <div className={styles.fileUpload}>
                      <input
                        className={styles.fileInput}
                        type="file"
                        id="formFile"
                        accept="image/*"
                      />
                      <label htmlFor="formFile" className={styles.fileLabel}>
                        <BsImageFill className={styles.fileIcon} />
                        <span className={styles.fileText}>
                          Clique para selecionar uma imagem
                        </span>
                      </label>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Navigation Buttons */}
          <div className={styles.navigation}>
            {currentStep > 1 && (
              <button
                type="button"
                onClick={handlePrevious}
                onMouseDown={(e) => e.preventDefault()}
                className={`${styles.button} ${styles.buttonSecondary}`}
              >
                <BsArrowLeft className={styles.buttonIcon} />
                Voltar
              </button>
            )}

            {currentStep < totalSteps ? (
              <button
                type="button"
                onClick={handleNext}
                onMouseDown={(e) => e.preventDefault()}
                className={`${styles.button} ${styles.buttonPrimary}`}
              >
                Próximo
                <BsArrowRight className={styles.buttonIcon} />
              </button>
            ) : (
              <button
                type="button"
                onClick={(e) => {
                  if (!(e as React.MouseEvent).isTrusted) {
                    console.warn("⛔ Click não confiável bloqueado (isTrusted=false)");
                    return;
                  }
                  const nonce = Math.random().toString(36).slice(2, 10);
                  submitNonceRef.current = nonce;
                  performSubmit(nonce);
                }}
                disabled={isSubmitting}
                className={`${styles.button} ${styles.buttonPrimary}`}
              >
                <BsCheckCircleFill className={styles.buttonIcon} />
                {isSubmitting ? "Enviando..." : "Criar Solicitação"}
              </button>
            )}
          </div>
  </div>
      </div>
    </main>
  );
}
